### ISSUE TITLE
 NCP380HMU21AATBG (replace)

### ISSUE THREAD

**Issue by r13doc** [SensorsIot/SuperPower#37]
Hi, RPI shcematic  in  Pi-Output-Protection.sch has  NCP380HMU21AATBG, and it is max 2.1A. (Current Limit:♦User adjustable from 500 mA to 2.1 A from dataasheet )
but I use Rasp4( with display 7  inch) and other   -  it need about 3A 
Can I remake your schematic and replace NCP380HMU21AATBG to  NX5P3090UKZ (3.3A)for example or others????????

**Comment by sethkaz** [comment]
Yes, you are more than welcome to take the design files (schematic and PCB) and modify as you wish.

**Comment by r13doc** [comment]
Thanks!!!
