### ISSUE TITLE
Is the semiconductor crisis finally over?

### ISSUE THREAD

**Issue by adoconnection** [SensorsIot/SuperPower#44]
Hi all, it seems component shortages are doing to an end, so is there a way to make a new spin?

@SensorsIot @sethkaz @Tobi3566 @dr-stefan-krank @wassfila

**Comment by SensorsIot** [comment]
The project team stopped existing long time ago :-(

**Comment by XNinety9** [comment]
Sorry to read that :(
What's the project's status? Is its content useable @SensorsIot ?

**Comment by SensorsIot** [comment]
The project has been stopped and the documentation is not up-to-date AFAIK

**Comment by dr-stefan-krank** [comment]
Some of us are still here, but the project would have to be rolled up from the ground up. With the newer ESP32 models and their much improved deep sleep current and native USB connection, reviving this project isn't valuable anymore.
I'm here if something comes along that isn't covered by an already made board. Happy to be part of a project again.

**Comment by sethkaz** [comment]
On the Raspberry Pi side, there are now a bunch of battery backup options available which meet many of the same features.  Admittedly, they aren't open-source, but they do meet that need.
