### ISSUE TITLE
How about this for "SuperPower"?

### ISSUE THREAD

**Issue by vitalykorolev** [SensorsIot/SuperPower#7]
Adafruit just released a Universal USB / DC / Solar Lithium Ion/Polymer charger
Looks to me like it checking a lot of the right boxes, but I'm not an expert.
[https://www.adafruit.com/product/4755](https://www.adafruit.com/product/4755)
![image](https://user-images.githubusercontent.com/1957746/93538624-6c92ce80-f903-11ea-8cc4-598c2cb624f8.png)

**Comment by wassfila** [comment]
looks, good, this can go to the discord channel ready-made-boards, and I'll consider it for the competitive market analysis spreadsheet from the google drive.
We have two sheets, one for charging boards and one specifically for ESP32 charging boards.
https://drive.google.com/drive/mobile/folders/1w3U5OjFCr0vc1ZHyUKympC7aVEZiL1S2/12vNKP3u-Tji_rn3P-HrK09HfeL8PdmIe?sort=13&direction=a

**Comment by rik94566** [comment]
here is one I found for RPi and thinking about giving a go.  I do not is it
on the list as yet, but might be good to evaluate as well.

https://www.robotshop.com/en/watchdog-battery-backup-raspberry-pi.html

**Comment by Informaticore** [comment]
acknowledged closing
